version: 2.1
orbs:
  react-native: react-native-community/react-native@5.1.0
jobs:
  node:
    working_directory: ~/demo-react-native

    steps:
      - checkout

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: ~/demo-react-native
          paths:
            - node_modules

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

workflows:
  node:
    jobs:
      - node
